import Head from "next/head"
import { useState } from "react"
import { PrefectureSelect } from "components/organisms/PrefectureSelect"
import { Prefecture } from "types/apiResponses"
import styles from "styles/Home.module.css"
import { PopulationGraph } from "components/organisms/PopulationGraph"

export default function Home() {
  const [checkedPrefectures, setCheckedPrefectures] = useState<Prefecture[]>([])
  return (
    <div className={styles.container}>
      <Head>
        <title>ゆめみ コードチェック課題</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.title}>ゆめみ コードチェック課題</div>
        <section id="prefecture_select_section">
          <h2>都道府県を選択する</h2>
          <PrefectureSelect onChangeCheck={setCheckedPrefectures} />
        </section>
        <section id="population_graph_section">
          <h2>人口構成</h2>
          <PopulationGraph prefectures={checkedPrefectures} />
        </section>
      </div>
    </div>
  )
}
